apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
  labels:
    app: config-service-deployment
spec:
  selector:
    matchLabels:
      app: config-service-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: config-service-deployment
    spec:
      containers:
      - name: config-service-deployment
        image: derflinger/config-service
        ports:
        - containerPort: 8081