apiVersion: apps/v1
kind: Deployment
metadata:
  name: subir-data-service
  labels:
    app: subir-data-service
spec:
  selector:
    matchLabels:
      app: subir-data-service
  replicas: 2
  template:
    metadata:
      labels:
        app: subir-data-service
    spec:
      containers:
        - name: subir-data-service
          image: derflinger/subir-data-service:latest
          ports:
            - containerPort: 8082
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password

---
apiVersion: v1
kind: Service
metadata:
  name: subir-data-service
  labels:
    app: subir-data-service
spec:
  selector:
    app: subir-data-service
  ports:
    - nodePort: 3002
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort