server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA:localhost}:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: subirData-service
          uri: lb://subirData-service
          predicates:
            - Path=/fileUpload/**
        - id: subirPorcentaje-service
          uri: lb://subirPorcentaje-service
          predicates:
            - Path=/file-percentage/**
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedor/**
        - id: registroQuincena-service
          uri: lb://registroQuincena-service
          predicates:
            - Path=/quincena/**
